---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
remote_theme: woodcock3/city-jekyll
exclude: [CNAME, README.md, npm.md, SECURITY.md, LICENSE.md, .gitignore, package.json, package-lock.json, postcss.config.js, .browserslistrc]
permalink: /:title ## disables post output
url: "https://cecleeds.github.io"
baseurl: "/"
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:              "City Evangelical Church"
keywords:           "City, evangelical, church, Leeds, best, christian, Jesus, bible, gospel, Christ, God, Faith, Lord"
description:        "A Jekyll theme &amp; Sass Boilerplate"
author:             "woodcock3"
source_link:        "https://github.com/woodcock3/city-jekyll"
favicon:            "/assets/img/favicon/favicon.ico"
favicon_16:         "/assets/img/favicon/favicon-16x16.png"
favicon_32:         "/assets/img/favicon/favicon-32x32.png"
touch_icon:         "/assets/img/favicon/apple-touch-icon.png" ## City logo as apple touch icon
safari_pinned_tab:  "/assets/img/favicon/safari-pinned-tab.svg" ## put safari pinned tab svg icon here

google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  white:        '#f8f8f8'
  black:        '#2e2e2e'
  ckyellow:     '#febd2e'
  ckblue:       '#01a8ff'
  teal:         '#009688'
  cityorange:   '#f19426'
  cityblue:     '#259cd3'
  citygreen:    '#06892f'
  grey:         '#cdcdcd'
  darkgrey:     '#404040'
  whiteish:     '#fafafa'
  jetblack:     'black'
  sowhite:      'white'

kramdown:
  auto_ids:  false

collections_dir: pages

collections:
  home:
    output: true
    permalink: /
  sunday:
    output: true
    permalink: /sunday/
  media:
    output: true
    permalink: /media/

### sass
sass:
  sass_dir: '_sass'
  style: expanded
