---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: pages/_drafts
  label: Drafts
  create: documents
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: pages/_media
  label: Media
  create: documents
  match: "**/*"
- type: directory
  path: pages/_students
  label: Students
  create: documents
  match: "**/*"
- type: directory
  path: pages/_kids-youth
  label: Kids and youth
  create: documents
  match: "**/*"
- type: directory
  path: pages/_connect
  label: Connect
  create: documents
  match: "**/*"
- type: directory
  path: pages/_about-us
  label: About us
  create: documents
  match: "**/*"
- type: directory
  path: pages/_whats-on
  label: Whats on
  create: documents
  match: "**/*"
- type: directory
  path: pages/_sunday
  label: Sunday
  create: documents
  match: "**/*"
- type: directory
  path: pages/_home
  label: Home
  create: documents
  match: "**/*"
upload_dir: assets/img
public_path: "/assets/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6-node12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
