---
label: Default
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: collection_type
  label: collection_type
- type: text
  name: layout
  label: layout
- type: text
  name: container-size
  label: container-size
- type: number
  name: heading
  label: heading
- type: field_group_list
  name: action-card
  label: action-card
  fields:
  - type: text
    name: title
    label: title
  - type: text
    name: bg
    label: bg
  - type: text
    name: content
    label: content
  - type: text
    name: href
    label: href
